### ISSUE TITLE
Unable to compile  primefaces-applicant-portlet

### ISSUE THREAD

**Issue by theonn2** [liferay/liferay-faces-bridge-impl#108]
Cannot compile demo -> primefaces-applicant-portlet

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.849 s
[INFO] Finished at: 2016-08-05T14:17:20-05:00
[INFO] Final Memory: 10M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project com.liferay.faces.demo.primefaces.applicant.portlet: Could not resolve dependencies for project com.liferay.faces.demo:com.liferay.faces.demo.primefaces.applicant.portlet:war:5.0.0-SNAPSHOT: Could not find artifact org.apache.portals.pluto:portlet-api:jar:3.0-SNAPSHOT in liferay-faces-snapshots (https://oss.sonatype.org/content/groups/public/) -> [Help 1]

missing dependecy not found anywhere 

org.apache.portals.pluto:portlet-api:jar:3.0-SNAPSHOT

**Comment by stiemannkj1** [comment]
@theonn2, please follow the instructions [here](https://web.liferay.com/community/forums/-/message_boards/message/74036013#aui_3_4_0_1_3238):

> If you just want to test out the primefaces-applicant-portlet, you can try [downloading a SNAPSHOT of it](https://oss.sonatype.org/content/repositories/snapshots/com/liferay/faces/demo/com.liferay.faces.demo.primefaces.applicant.portlet/4.0.0-SNAPSHOT/com.liferay.faces.demo.primefaces.applicant.portlet-4.0.0-20160805.183107-130.war).

> If a SNAPSHOT is not enough, and you need to build the primefaces-applicant-portlet from source for Liferay 7.0:

> 1. Clone [the liferay-faces-bridge-impl repo](https://github.com/liferay/liferay-faces-bridge-impl):

>         git clone https://github.com/liferay/liferay-faces-bridge-impl.git

> 2. Checkout the `4.x` branch.

>         git checkout 4.x

> 3. Navigate to the primefaces-applicant-portlet:

>         cd demos/primefaces-applicant-portlet

> 4. Build the portlet for Liferay 7.0:

>        mvn clean install -P liferay

> 5. Copy the portlet to Liferay 7.0's **`deploy/`** folder:

>     cp target/primefaces-applicant-portlet-4.0.0-SNAPSHOT.war $LIFERAY_70_HOME/deploy/

Please let us know if you have any other issues [on our forums]() or in [our official JIRA issue tracker](https://issues.liferay.com/browse/FACES-2871?jql=project%20%3D%20FACES).

**Note:** if you are building for a portal other than Liferay 7.0, you will need to checkout the correct version according to [our version scheme](https://dev.liferay.com/develop/tutorials/-/knowledge_base/6-2/understanding-the-liferay-faces-version-scheme#liferay-faces-version-scheme-for-releases-after-liferay-faces-ga6) instead of `4.x`.

**Comment by theonn2** [comment]
Version 4.x builds and deploys fine. 5.x as per the response.. is just not ready.
